import prisma from '../db/prisma';
import { logger } from '../utils/logger';
import { encrypt } from '../utils/encryption';
import { ShopifyClient } from '../clients/shopify.client';

export interface TenantRegistrationInput {
  shopDomain: string;
  accessToken: string;
  apiKey?: string;
  apiSecret?: string;
}

export interface TenantResponse {
  id: string;
  shopDomain: string;
  createdAt: Date;
  updatedAt: Date;
}

export class TenantService {
  /**
   * Register a new tenant with Shopify credentials
   * Validates credentials against Shopify API before storing
   */
  async registerTenant(input: TenantRegistrationInput): Promise<TenantResponse> {
    const { shopDomain, accessToken, apiKey, apiSecret } = input;

    // Normalize shop domain (remove protocol, trailing slashes, etc.)
    const normalizedDomain = this.normalizeDomain(shopDomain);

    // Check if tenant already exists with this shop domain
    const existingTenant = await prisma.tenant.findUnique({
      where: { shopDomain: normalizedDomain },
    });

    if (existingTenant) {
      logger.warn(`Attempted to register duplicate tenant: ${normalizedDomain}`);
      throw new Error('A tenant with this shop domain already exists');
    }

    // Validate Shopify credentials by making an API call
    const shopifyClient = new ShopifyClient({
      shopDomain: normalizedDomain,
      accessToken,
    });

    try {
      await shopifyClient.validateCredentials();
    } catch (error: any) {
      logger.error(`Failed to validate Shopify credentials for ${normalizedDomain}: ${error.message}`);
      throw new Error(`Shopify credential validation failed: ${error.message}`);
    }

    // Encrypt sensitive credentials before storing
    const accessTokenEncrypted = encrypt(accessToken);
    const apiSecretEncrypted = apiSecret ? encrypt(apiSecret) : null;

    // Create tenant record with unique identifier (generated by database)
    const tenant = await prisma.tenant.create({
      data: {
        shopDomain: normalizedDomain,
        accessTokenEncrypted,
        apiKey: apiKey || null,
        apiSecretEncrypted,
      },
    });

    logger.info(`Tenant registered successfully: ${tenant.id} (${normalizedDomain})`);

    return {
      id: tenant.id,
      shopDomain: tenant.shopDomain,
      createdAt: tenant.createdAt,
      updatedAt: tenant.updatedAt,
    };
  }

  /**
   * Get tenant by ID
   */
  async getTenantById(tenantId: string): Promise<TenantResponse | null> {
    const tenant = await prisma.tenant.findUnique({
      where: { id: tenantId },
    });

    if (!tenant) {
      return null;
    }

    return {
      id: tenant.id,
      shopDomain: tenant.shopDomain,
      createdAt: tenant.createdAt,
      updatedAt: tenant.updatedAt,
    };
  }

  /**
   * Get tenant by shop domain
   */
  async getTenantByDomain(shopDomain: string): Promise<TenantResponse | null> {
    const normalizedDomain = this.normalizeDomain(shopDomain);
    
    const tenant = await prisma.tenant.findUnique({
      where: { shopDomain: normalizedDomain },
    });

    if (!tenant) {
      return null;
    }

    return {
      id: tenant.id,
      shopDomain: tenant.shopDomain,
      createdAt: tenant.createdAt,
      updatedAt: tenant.updatedAt,
    };
  }

  /**
   * Normalize shop domain to a consistent format
   * Removes protocol, www, trailing slashes, and converts to lowercase
   */
  private normalizeDomain(domain: string): string {
    return domain
      .toLowerCase()
      .replace(/^https?:\/\//, '')
      .replace(/^www\./, '')
      .replace(/\/$/, '')
      .trim();
  }
}

export const tenantService = new TenantService();
